kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-inventory
subjects:
- kind: ServiceAccount
  name: multicluster-inventory
  namespace: default
roleRef:
  kind: ClusterRole
  name: multicluster-inventory
  apiGroup: rbac.authorization.k8s.io
